application_port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
application:
  port: 8000
  host: 127.0.0.1
  base_url: http://127.0.0.1
email_client:
  base_url: https://api.mailjet.com/v3.1
  sender_email: "mini_muz_11@hotmail.co.uk"
  authorization_token: "my-auth-token"
  timeout_milliseconds: 1000
